- name: Configure | Tune sysctl parameters
  when: keepalived_configure_kernel
  block:
    - name: Configure | Load sysctl parameters
      ansible.builtin.include_vars: sysctl_conf.yml

    - name: Configure | Tune sysctl parameters
      ignore_errors: true
      ansible.posix.sysctl:
        name: '{{ item.key }}'
        value: '{{ item.value }}'
        sysctl_set: true
        state: present
        reload: true
      loop: '{{ keepalived_sysctl_conf | dict2items }}'

- name: Configure | Create keepalived config
  block:
    - name: Configure | Create keepalived config
      ansible.builtin.template:
        src: etc/keepalived/keepalived.conf.j2
        dest: /etc/keepalived/keepalived.conf
        mode: "0640"
        backup: true
      register: _keepalived_config_changed
      notify: restart keepalived

    - name: Configure | Validate keepalived config
      ansible.builtin.shell: /usr/sbin/keepalived -t -f /tmp/keepalived.conf
      when: _keepalived_config_changed.changed
      changed_when: false

  rescue:
    - name: Configure | Restore previous keepalived config
      ansible.builtin.copy:
        dest: /etc/keepalived/keepalived.conf
        src: _keepalived_config_changed.backup_file
        remote_src: true
        mode: "0640"
      when: _keepalived_config_changed.backup_file is defined

  always:
    - name: Configure | display config changes
      ansible.builtin.debug:
        var: _keepalived_config_changed.diff
      when: _keepalived_config_changed.changed
