- name: Dummy Interface | Add dummy module
  community.general.modprobe:
    name: dummy
    state: "{{ keepalived_dummy_interface | ternary('present','absent') }}"
    params: "numdummies=1"

- name: Dummy Interface | Ensure interfaces.d is present
  ansible.builtin.file:
    path: /etc/network/interfaces.d
    state: directory

- name: Present
  when: keepalived_dummy_interface
  block:
    - name: Dummy Interface | Configure dummy module
      ansible.builtin.template:
        src: "etc/modules-load.d/dummy.conf.j2"
        dest: "/etc/modules-load.d/dummy.conf"
        owner: root
        group: root
        mode: "0744"

    - name: Dummy Interface | Create interface config
      ansible.builtin.template:
        src: etc/network/interfaces.d/dummy.j2
        dest: "/etc/network/interfaces.d/dummy{{ keepalived_dummy_number }}.cfg"
      notify: restart dummy interface

    - name: Dummy Interface | Remove obsolete interface config
      ansible.builtin.file:
        path: "/etc/network/interfaces.d/dummy{{ keepalived_dummy_number }}"
        state: absent

- name: Dummy Interface | Cleanup config files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  when:
    - not keepalived_dummy_interface
    - hostvars[host]['ansible_dummy'~keepalived_dummy_number] is defined
  notify:
    - stop dummy interface
  loop:
    - "/etc/network/interfaces.d/dummy{{ keepalived_dummy_number }}.cfg"
    - /etc/modules-load.d/dummy.conf
