---
- name: Regather network facts
  ansible.builtin.setup:
    gather_subset:
      - "!all"
      - "!min"
      - "network"
  tags: configure

- name: Install keepalived
  ansible.builtin.import_tasks: install.yml

- name: Configure
  ansible.builtin.import_tasks: configure.yml
  tags: configure
