---
- name: Regather network facts
  ansible.builtin.setup:
    gather_subset:
      - "!all"
      - "!min"
      - "network"

- name: Install keepalived
  ansible.builtin.import_tasks: install.yml

- name: configure
  ansible.builtin.import_tasks: configure.yml
